name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Prospector
      run: |
        pip install dodgy mccabe mypy  pycodestyle pydocstyle pylint
        python -m pip install prospector
    - name: Run Prospector
      run: |
        pwd
        ls -ltr |grep py
        prospector . --strictness veryhigh  prospector . --tools pyflakes,pep8 --output-format text
          
    #- name: Install dependencies
     # run: |
      #  python -m pip install --upgrade pip
       # pip install pylint
        
    #- name: Analysing the code with pylint
     # run: |
      #  pylint $(git ls-files '*.py')
